### ISSUE TITLE
Felipe Nascimento de Moura: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by felipenmoura** [goyalsid/phageParser#10]
I've always been interested in genes, chemistry, phiisics...etc, but had never had time, or meanings to work or learn more about it!
I think this initiative is quite interesting and appealing!
Working for about 10 years with technology/programming/analysing/building/modelling, I have worked at Terra Networks as a Senior Web Developer and Analyst.
I'm passionate about music, movies, etc.<p><br><blockquote>This issue was created by @felipenmoura via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Hi Felipe, my apologies for leaving you hanging! I'm a new project lead on this project, and if you're still interested in getting involved, you are most welcome to. Is there anything in particular that caught your eye that you'd like to work on?

**Comment by felipenmoura** [comment]
Hi.
Yeah, sure thing!
I am passioned to science, space, particles, biology, etc...
what could I do to help?
:)

**Comment by mbonsma** [comment]
In general, feel free to tackle anything at all in the "Issues" section! 

To get started, you could try running the code that other people have created so far to familiarize yourself with the project and also to check if things are working as they should. Some of the usage is described in the `ReadMe`. Related to that: do you know anything about writing tests for code? I have no experience in that, so it would be great if someone would be able to create some tests for the code that's been created so far.
