### ISSUE TITLE
anderson89marques: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by anderson89marques** [goyalsid/phageParser#11]
Hi, i'am Anderson Marques from Belém, Pará, Brasil (Brazil).
I'm Computer Science student.

My interest is to work on a project whose outcome may help people.

i'm python(i like more) programer.
i program too in Java, C/C++, Android, Grails...

I don't know about medicine area, but if you help me understand better this area, i can help this project too.

Sorry my bad english, i am studying to make it better :D <p><br><blockquote>This issue was created by @anderson89marques via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Hi Anderson, I'm a new project lead on this project. I'm sorry for the long delay! If you're still interested in contributing, we'd love to have you. I'm hoping to put up some relevant reading material in the ReadMe soon, so that would be a good place to get your feet wet.
