### ISSUE TITLE
abhirathb: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by abhirathb** [goyalsid/phageParser#12]
Hi all,
I am a third year student from India. I'm a part of a program specifically for the confluence of Computer Science and Natural Sciences in IIIT-Hyderabad.  Thus I have decent knowledge of biological systems and am also well trained in Computer Science. 
I hope to prove useful!<p><br><blockquote>This issue was created by @abhirathb via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Hello and welcome! I'm a new project lead, and I'm sorry for the long delay. Your background sounds very relevant to this project - is there anything you've seen here that you'd specifically like to work on?
