### ISSUE TITLE
Natchar: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by natchar** [goyalsid/phageParser#13]
<p><br><blockquote>This issue was created by @natchar via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Welcome Natchar! I'm Madeleine, one of the project leads for this project. 

This weekend is the Toronto Open Science Code Sprint (hosted by Mozilla Science Lab), and lots of us will be hacking away at the issues in the Code Sprint milestone. If you happen to be around, you're most welcome to join, or you can hang out via [Mozilla's IRC channel] (http://www.mozillascience.org/join-the-sciencelab-on-irc/). 

What kinds of things are you interested in?
