### ISSUE TITLE
Generate Interaction List

### ISSUE THREAD

**Issue by mbonsma** [goyalsid/phageParser#16]
After obtaining and sorting a list of bacteria and their spacers ( #14  ), BLASTing the spacers against the phage database ( #15 ), and cleaning up the output ( #1 ), we want a nice list of bacteria and which phages they interact with that can be used to do analysis or create visualizations. 

For each bacteria species identified earlier, we want a file of interactions that looks something like this:

bacteria name, phage 1 name, phage 2 name, ..., phage n name

There may be some sticky biology issues with how to interpret the phage db BLAST output in the cases where there's no clear phage "winner" among the hits to each spacer.

**Comment by BillMills** [comment]
Depending on how we tackle #17, different things might make sense for storing this info; could be a simple JSON encoding for easy consumption by a web app, or stuffing it into a database - suggestions welcome :)

**Comment by mbonsma** [comment]
JSON was chosen, since that's what cytoscape.js uses. Implemented in `interactions.py`.
