### ISSUE TITLE
Genome Fetcher

### ISSUE THREAD

**Issue by BillMills** [goyalsid/phageParser#2]
Once a match is found between some genetic code of interest and a phage via the process described in #1, it's interesting to learn about the surrounding genetic code in the phage; not just the matched string that the BLAST query returned, but what genes are nearby that sequence, as well.  The BLAST query doesn't give us this; we need to find that information elsewhere.

NCBI provides a command-line tool, the [SRA Toolkit](http://www.ncbi.nlm.nih.gov/books/NBK158900/), to download extensive genomic data from their open database, genbank.  This is done via *accession numbers*, essentially unique identifiers for genomic data in their database.  Furthermore, phagesdb.org kindly provides a master metadata table, found here in `PhagesDB_Data.txt` that contains the accession numbers and genbank status of each of their phages.

From these resources, two python functions are needed:
 - function `getAccession(name)` that takes the name of a phage, checks if it's in genbank, and if so, returns the corresponding accession number.  The phage name is contained as a string in the first column of `PhagesDB_data.txt`; the genbank status is in column 4 as 'True' (if present in genbank) or 'False' (if not), and the accession number is a string in column 5.  So, `getAccession('Arbiter B2')` should return the string 'JN618996', while `getAccession('Ariel   J')` doesn't have a genbank entry, so should return perhaps 0.

 - function `fetchAccession(accession)`, which takes a string argument `accession` and uses the SRA toolkit mentioned above to download the corresponding dataset.  Once installed and working, the SRA toolkit can be used as: 
`prefetch <accession number>` 
to download the dataset corresponding to `accession number`.

**Comment by mbonsma** [comment]
Hi Bill, I'm a Master's student in Sid's group working on bacteria-phage interactions. 

"Nuccore", to the best of my knowledge, refers to the NCBI Nucleotide Database, which itself includes a few other databases. It seems like a fine choice of database, since it looks like it contains the broadest data. It's good to know that it could be changed though.

I'm not sure what rettype="gb" means though.

**Comment by BillMills** [comment]
Cool, thanks @mbonsma for clearing that up - actually, I've been meaning to come back to this, since I was chatting with some bioinformatics people the other day, and they pointed out that it's really important to query NCBI properly (via biopython), lest we run afoul of their access policies - but as I mentioned above, biopython appears to be a dependency here, so I think we're ok.

Anyway - I'd love to chat with you sometime more broadly about this project before the Toronto event; I was guiding things day-to-day for this project last year, but am really excited to hand off to you, hear what you have planned and support you in any way possible. Get ahold of me at bill@mozillafoundation.org if you'd like to discuss!

**Comment by mbonsma** [comment]
The example @BillMills gave (`cat test.accession | python acc2gb.py somename@somehost.com > out.gb`) works great. Incidentally, it seems to work regardless of what type of accession number you give it. For example, I tried `NC_015138`, which is the format that the bacteria and archaea are in, and it also works. 

The only thing is that it seems to be returning an abbreviated version of the data - on the website, there's an option to save just a 'Genbank' record or a 'Genbank (full)' record. What it's returning now is the Genbank record. Maybe this is what that parameter `rettype=gb` is referring to (gb = Genbank?)? I'll look into it. There are some situations in which we'd want the full record (for example, to see all the coding sequences and the DNA sequence itself).

**Comment by mbonsma** [comment]
Got it - setting `rettype` to `rettype = "gbwithparts"` will fetch the entire record. I changed this in `acc2gb.py`.

**Comment by mbonsma** [comment]
Now all that remains in this issue is the function `getAccession(name)`.

**Comment by JJ** [comment]
Let me see if I got this straight. Can `getAccession`  be an independent script? So can it be done in Perl?

**Comment by mbonsma** [comment]
Yup. So far everything is modular, so each step is more or less independent. It could be done in perl. And just to clarify, this would be using the file `PhagesDB_data.txt`.

**Comment by JJ** [comment]
Great, thanks!

2015-06-05 17:09 GMT+02:00 mbonsma <notifications@github.com>:

> Yup. So far everything is modular, so each step is more or less
> independent. It could be done in perl. And just to clarify, this would be
> using the file PhagesDB_data.txt.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goyalsid/phageParser/issues/2#issuecomment-109322899>.
>



-- 
JJ

**Comment by mbonsma** [comment]
`getAccession.py` works well, but it would be good to rig it so that it reads in a list of names and outputs a file - similar to the functioning of `acc2gb.py`.

**Comment by JJ** [comment]
Was this done?

**Comment by mbonsma** [comment]
My most recent comment - no, that hasn't been done yet.

**Comment by mbonsma** [comment]
I think `getAccession` is good as it exists now, and if we happen to need to modify it to work with a future workflow we can do that (and make a new issue). So, I'm closing this as finished. Thanks @shirishgoyal, @JJ, and @BillMills for all the awesome work!

**Comment by JJ** [comment]
Thanks, Madeleine.

2016-06-02 15:58 GMT+02:00 Madeleine Bonsma <notifications@github.com>:

> I think getAccession is good as it exists now, and if we happen to need
> to modify it to work with a future workflow we can do that (and make a new
> issue). So, I'm closing this as finished. Thanks @shirishgoyal
> <https://github.com/shirishgoyal>, @JJ <https://github.com/JJ>, and
> @BillMills <https://github.com/BillMills> for all the awesome work!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/goyalsid/phageParser/issues/2#issuecomment-223299873>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAB9IZf-sZVgQfF6GDjgqI2FZ8sP4n3ks5qHuGWgaJpZM4CZdDz>
> .
>



-- 
JJ
