### ISSUE TITLE
Bacteria names and info from NCBI accession #

### ISSUE THREAD

**Issue by mbonsma** [goyalsid/phageParser#27]
Using RefSeq accession numbers, we want to extract info from GenBank about bacteria (and possibly also phages). This could all go in a reference file with several columns: accession number, bacteria name (genus and species), strain identifier, and optional other information we might want. The function `acc2gb.py` extracts Genbank files based on a list of one or more accession numbers. 

Example output reference file: 

> accession number, bacteria name (genus and species), strain identifier, organism lineage
> NC_000853,Thermotoga maritima, MSB8, Bacteria; Thermotogae; Thermotogales; Thermotogaceae; Thermotoga

It would be cool to have the option of adding more data if it exists. For example, in this section of the `Genbank_example.txt` file there are a bunch of other fields, and some of them are filled out. Not all of them are interesting, but it would be good to be able to collect those fields. 

```
            investigation_type  :: bacteria_archaea
            project_name        :: Acidovorax avenae avenae ATCC 19860
            collection_date     :: 1909
            lat_lon             :: Missing
            depth               :: Missing
            alt_elev            :: Missing
            country             :: USA
            environment         :: Host
            num_replicons       :: 1
            ref_biomaterial     :: ATCC 19860, DSM 7227
            biotic_relationship :: Free living
            trophic_level       :: Missing
            rel_to_oxygen       :: Aerobe
            isol_growth_condt   :: Missing
            sequencing_meth     :: WGS
            assembly            :: Newbler v.2.3 (pre-release)
            finishing_strategy  :: Finished
            GOLD Stamp ID       :: Gi04300
            Type Strain         :: Yes
            Isolation Site      :: maize leaf
            Isolation Comments  :: isolated by A.Ullstrup
            Cell Shape          :: Rod-shaped
            Motility            :: Motile
            Sporulation         :: Nonsporulating
            Temperature Range   :: Mesophile
            Gram Staining       :: Gram-
            Diseases            :: Bacterial fruit blotch
            Phenotypes          :: Pathogen
```

Note: the lineage information will be useful for asking general questions. For example, we might want to know whether Type I CRISPR systems are more common in bacteria or archaea.

**Comment by mbonsma** [comment]
The CRISPRdb website has a [list](http://crispr.u-psud.fr/crispr/BLAST/CRISPRsdatabase) that sort of seems like the right thing, except they're using the NCBI taxon ID instead of the actual sequence accession number. 

Example from CRISPRdb file:
243274|Thermotoga maritima MSB8

What we want:
NC_000853,Thermotoga maritima, MSB8

**Comment by mbonsma** [comment]
The 'Comments' section of the Genbank file often has other information, such as where the organism was isolated, Gram staining, etc. It would be good to have the option to pull other fields if they exist (they may often not). 

It will be helpful to be able to access Genbank for other information in general, so I think my previous comment about CRISPRdb can be ignored.

**Comment by darwinhang** [comment]
@mbonsma I'd be interested in working on this.

**Comment by mbonsma** [comment]
@darwinhang Awesome! That would be fantastic. I think there are a few different routes this could go depending on what you're interested in and feel like doing. This issue is closely related to #47 (Extract data from Python object generated with NCBI Entrez), and there's a twin issue for a different database (Issue #52), so if you want you could check out all three. 

Also I just made a [flow chart](https://raw.githubusercontent.com/goyalsid/phageParser/master/phageParser_workflow_diagram.png) about the project, which hopefully makes it a bit clearer how the pieces fit together. 

Let me know if there's anything I can do to smooth your path.

**Comment by darwinhang** [comment]
@mbonsma Thanks for sharing the flow chart. It does seem like it would make sense to work on this issue and #47  at the same time.

**Comment by mbonsma** [comment]
@darwinhang - I made [`bac_info_parser.py`](https://github.com/goyalsid/phageParser/commit/73e88ae26c63c1a5320afb14f27d92ffdcc015d7) that uses `Bio.SeqIO.parse` to read in Genbank files. It could probably be improved to be more versatile - right now I have it just extracting the bacteria name and taxonomy and making a dictionary. 

I think this can close issue #47 though. `Bio.SeqIO.parse` is the same as `Bio.SeqIO.read` mentioned in that issue; the only difference is that `parse` handles multiple records per file while `read` can only do single records.

**Comment by mbonsma** [comment]
Related - [organism_name_update](https://github.com/goyalsid/phageParser/blob/master/organism_name_update.py) fetches just the organism name from the NCBI accession # and adds it to the [crispr.sqlite](https://github.com/goyalsid/phageParser/blob/master/crispr.sqlite) database.
