### ISSUE TITLE
dmfinke: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by dmfinke** [goyalsid/phageParser#28]
<p><br><blockquote>This issue was created by @dmfinke via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Welcome Dayna! So cool that you found us :) Let me know if there's anything in particular you want to work on, or if you have ideas or anything like that.
