### ISSUE TITLE
Create project build

### ISSUE THREAD

**Issue by kinow** [goyalsid/phageParser#32]
A build, with some common tool like ant or Make, could help other developers to better understand the project. 

The documentation, in especial README, is helpful, but sometimes you just want to see the program workflow without having to read & execute all the commands. Plus, we can leverage from existing projects, like khmer, which is also written mainly in Python.

**Comment by kinow** [comment]
I believe this issue can be closed :-)

**Comment by mbonsma** [comment]
Agreed! Closing it up.

**Comment by kinow** [comment]
Thanks!
