### ISSUE TITLE
Using Make with Windows

### ISSUE THREAD

**Issue by mbonsma** [goyalsid/phageParser#34]
Following @kinow's make build for phageParser, I'm trying to run the example in the ReadMe on my Windows machine. 

GnuWin has a [Make utility](http://gnuwin32.sourceforge.net/packages/make.htm) that can be used from the Windows command prompt. It seems to be doing what it should (I can type `make -help` and it shows the help). I assumed that once that was working, I could just use exactly the same Make commands as in the example:

```
make filter_by_expect infile=data/blast-phagesdb.txt output=output/ threshold=0.21
```

I get this error:

```
"data/blast-phagesdb.txt" was unexpected at this time.
```

followed by a `make` error. 

I think it's a Windows cmd syntax problem, not a `make` problem. To be fair though, I know almost nothing about either. I tried various arrangements of quotes around the filenames and switching the slash direction (Windows uses the other one for folders), but still the same error.

**Comment by mbonsma** [comment]
If it's not immediately obvious, I can always run it on a Linux server I have access to, so it's not too urgent. It might be good to know anyway for other people who want to use Windows though, so thanks for giving it a whirl!

**Comment by kinow** [comment]
Had problems running in Windows, as I have an old Windows XP VM (yup, XP :). But running make filter_by_expect I get the following message:

```
"" was unexpected at this time [guard-infile] Error 255
make: ***
```

I'll need to get another VM to test that Make target, as that's dynamically created (there's a guard-% that gets resolved to the parameter name, infile in this case).
