### ISSUE TITLE
Determine CRISPR type from Cas genes in bacterial/archaeal genome

### ISSUE THREAD

**Issue by mbonsma** [goyalsid/phageParser#36]
CRISPR loci are generally classified into three types: Type I, Type II, and Type III. The type is based on which particular genes are associated with the locus out of all the known CRISPR-associated (Cas) genes. These Cas genes have descriptive names like 'cas1', 'cas2', 'cas3', and so on. 

Cas3, cas9, and cas10 are the signatures of Types I, II, and III respectively. Given a bacterial genome, then, we can determine which CRISPR types are present in the genome by searching that organism's Genbank file ([example](https://github.com/goyalsid/phageParser/blob/master/data/NC_015138_genbank.txt)) for annotated Cas genes. This would provide a way to answer broad questions about the prevalence of certain CRISPR types in different scenarios, and combined with information from #27 would be a powerful tool to pull out interesting stuff. 

We need a function that will take an accession number and optional start and end points and search for Cas genes in Genbank. It should return a list of all Cas genes found within the start and end points (if applicable), and the CRISPR type if it can be determined. 

Issue #2 has produced a function `acc2gb.py` that pulls the relevant data from Genbank given an accession number.

After that, you get a file like [this one](https://github.com/goyalsid/phageParser/blob/master/data/NC_015138_genbank.txt) which is downloaded from [this website](http://www.ncbi.nlm.nih.gov/nuccore/326314823?report=genbank#feature_326314823). The function should search through this file until it finds a gene whose start and end positions are between the start and end positions passed to the function. Then at the line that says `/product=` followed by a name, if one of the words in the name has 'Cas' in it, grab it. If it happens to be cas3, cas9, or cas10, update that CRISPR type to I, II, or III respectively. 

Example Cas gene:
```
     gene         298983..299912
                     /locus_tag="ACAV_RS01305"
                     /old_locus_tag="Acav_0268"
     CDS             298983..299912
                     /locus_tag="ACAV_RS01305"
                     /old_locus_tag="Acav_0268"
                     /inference="EXISTENCE: similar to AA
                     sequence:RefSeq:WP_013592778.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="CRISPR-associated protein Cas1"
                     /protein_id="WP_013592778.1"
                     /db_xref="GI:503358117"
```

**Comment by daisieh** [comment]
I have some perl functions that do similar things in my repo (https://github.com/daisieh/phylogenomics/tree/master/lib) that might help with this. I don't know if perl is welcome here?

**Comment by mbonsma** [comment]
(Rewriting IRC comments) I've never used Perl, but there's no point re-inventing the wheel, so go for it!

**Comment by daisieh** [comment]
We're looking at this and now I'm realizing: is this just a regex for the genbank file? Like, two regex lines: `m/ORGANISM=/` and then `m/\/product=.*Cas/` or something similar?

**Comment by daisieh** [comment]
Do you need any other context around the product lines, or literally just the product lines?

**Comment by mbonsma** [comment]
The only possible context we would want would be the location in the genome of the gene - I think that's a few lines previous. But yeah, simple regex would be fine.

**Comment by mbonsma** [comment]
You could take a look at #27 after this - it would be very similar. It's not very well-written, but basically it would rely on the same file and just finding other stuff. In fact this issue could probably be combined with that.

**Comment by daisieh** [comment]
The version I pushed up right now does not get the gene location. I'll do that now.

**Comment by daisieh** [comment]
@mbonsma, can you explain what you want the output to look like when you say " If it happens to be cas3, cas9, or cas10, update that CRISPR type to I, II, or III respectively"? Do you want to update the genbank file with that information? How do you want it to look?

For example, if the product line says:
```
/product="CRISPR-associated protein Cas3"
```
what would you like the output to be?

**Comment by mbonsma** [comment]
I was thinking a new file, something like a column for the accession number, name, cas proteins, and crispr type(s).

**Comment by mbonsma** [comment]
So in your example there should be a row with the bacterium name and accession #, 'cas3', and 'type I'.

**Comment by JJ** [comment]
Can I be of help here? I'll go to the other repo.

**Comment by JJ** [comment]
@daisieh Maybe you could create an issue and assign it to me?

**Comment by daisieh** [comment]
Some other Vancouver sprinters are taking care of the next part of the task; this is just the first bit of the pipeline.

**Comment by morien** [comment]
submitted a pull request with a new perl script that addresses a good portion of what you're looking for, @mbonsma 

can be modified for CAS type, but for now it just counts unique protein products per organism, along with their kingdom (you could load the output into R and do your stats, produce some figures on bacteria vs archea, or whatever you like). a dictionary of all the CAS types/proteins and what group they belong to would help me, does that file already exist in the repo?

**Comment by mbonsma** [comment]
Looks cool @morien. The Cas type to CRISPR type is very straightforward:

Cas3 -> Type I
Cas9 -> Type II
Cas10 -> Type III

**Comment by mbonsma** [comment]
Okay boring perl help question: I'm getting an error 
```
'Can't locate File/Slurp/Tiny.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at cas_in_gb_v2.pl line8. BEGIN failed--compilation aborted at cas_in_gb_v2.pl line 8.
```

**Comment by mbonsma** [comment]
Also the server I'm using doesn't have perl 5.14, just 5.10 (which Abby said was buggy), so I changed the `use v5.14` line to `use v5.10`.

**Comment by daisieh** [comment]
@mbonsma: this isn't a stupid question at all: I think it would be safer to do this without that dependency (File:Slurp:Tiny); I'll rewrite it that way and then your problem will go away.

**Comment by daisieh** [comment]
@mbonsma: I sent a PR #43 which should run on your machine now.

**Comment by mbonsma** [comment]
This issue is very nearly done, which is awesome. It might be nice to have `cas_in_gb_v2.pl` write the output to a file instead of printing - is that doable?

**Comment by daisieh** [comment]
Very easy: I can either do it by hand, or you can call it as `perl cas_in_gb_v2.pl input_genbank_file.gb > output.txt`

**Comment by JJ** [comment]
Can do tomorrow

El viernes, 5 de junio de 2015, Daisie Huang <notifications@github.com>
escribió:
> Very easy: I can either do it by hand, or you can call it as perl
cas_in_gb_v2.pl input_genbank_file.gb > output.txt
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/bXmh6FL-1StfuUQgCeQh5u1fPgEHHM9MpGI43mTzNG9aKMUOaWw7wts6QLAEUNyP1sfJHn0fb2qBm09Q6yZ_k3c5zQp-CftNtECyPHG7Fu5EUhReMbp0k6lVfw0cTpDEQky2MTuaHzFKxq4TABF-p-THTsrewQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAB9B5sKGBG5onBwYsT1eTXC1F64IJCks5oQgvcgaJpZM4Et3Ws.gif
>

-- 
JJ

**Comment by mbonsma** [comment]
This can be closed - implemented with `cas_in_gb_v2.pl`
