### ISSUE TITLE
Perl error when running cas_in_gb_v2.p1

### ISSUE THREAD

**Issue by mbonsma** [goyalsid/phageParser#46]
The script `cas_in_gb_v2.pl` works without error on the file `Genbank_example.txt`, but when I ran `perl cas_in_gb_v2.pl "out_all_cleaned.gb" > output.txt` on a much larger file with ~1300 organisms, I got the error:
```
panic: sv_setpvn called with negative strlen at cas_in_gb_v2.pl line 22.
```

The files should be the same format-wise; the only difference is that the large file has no actual DNA data in it and it's much bigger. (When I ran it on a small subset of the large file, it works fine.)

@daisieh and @JJ, I couldn't assign either of you to the issue for some reason, but do either of you have any ideas as to what could be going on?

**Comment by JJ** [comment]
OMFG. That's Perl internal... sounds like can't swallow such a big file.
Please post that example file, as well as required output.

2015-06-09 18:49 GMT+02:00 mbonsma <notifications@github.com>:

> The script cas_in_gb_v2.pl works without error on the file
> Genbank_example.txt, but when I ran perl cas_in_gb_v2.pl "
> out_all_cleaned.gb" > output.txt on a much larger file with ~1300
> organisms, I got the error:
>
> panic: sv_setpvn called with negative strlen at cas_in_gb_v2.pl line 22.
>
> The files should be the same format-wise; the only difference is that the
> large file has no actual DNA data in it and it's much bigger. (When I ran
> it on a small subset of the large file, it works fine.)
>
> @daisieh <https://github.com/daisieh> and @JJ <https://github.com/JJ>, I
> couldn't assign either of you to the issue for some reason, but do either
> of you have any ideas as to what could be going on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goyalsid/phageParser/issues/46>.
>



-- 
JJ

**Comment by mbonsma** [comment]
Git bash wouldn't let me add a file so big - it's 4800 MB. If you think it's a size issue, I think since a file about 1/4 of the size worked, I'll just do it in pieces.

**Comment by JJ** [comment]
It's most probably a size issue.

You can upload big files to GitHub is you create a tag and do a Release.
But just upload it to Dropbox or Google Drive so that I can use it as an
example.

**Comment by JJ** [comment]
Besides, it will probably need refactoring the whole program to deal with
that kind of file, probably work directly on the source, maybe use the
query you used to get the file with SNA or something like that. Please give
me some details so that I can work it out.

**Comment by mbonsma** [comment]
I'm in the process of uploading the file, I'll send you a link when it's ready. To produce that file, I ran
```
cat bac_accession_list.txt | python acc2gb.py yourname@email.com > out_all.gb
```
(You'll need an NCBI account to run acc2gb.py)

Then I ran `trimGenbankDNA.py`, which produces the file `out_all_cleaned.gb`.

Those scripts and intermediate files are all on Github.

**Comment by mbonsma** [comment]
Here's a [link](https://drive.google.com/file/d/0B6JZXa8y_013TWE5b2ZwMXpzdE0/view?usp=sharing) to the file `out_all_cleaned.gb`.

**Comment by JJ** [comment]
OK, I get it. So it's kind of a pipeline, in which case I think, specially
for big amounts of data, which is by definition big data, it would be much
better to use another interchange format, JSON, XML, or whatever. With XML
you have a very efficient stream processing option called SAX which
processes the file as it arrives. Storing it in a database, or a NoSQL
database, would make more efficient ro process stuff in any format you
want. Even more so, maybe if everything works under a web service we might
be able to use some other kind of processing in-memory or using in-memory
databases... It all boils down to using a more efficient data structure to
store and easen the workflow.
I'll try to look into this, but off the top of my head I would say that the
best would be to create a single script.

Cheers

**Comment by JJ** [comment]
OK, will use it for tests.

2015-06-10 17:31 GMT+02:00 mbonsma <notifications@github.com>:

> Here's a link
> <https://drive.google.com/file/d/0B6JZXa8y_013TWE5b2ZwMXpzdE0/view?usp=sharing>
> to the file out_all_cleaned.gb.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goyalsid/phageParser/issues/46#issuecomment-110797183>
> .
>



-- 
JJ

**Comment by mbonsma** [comment]
Thanks @JJ, that makes sense to me.

**Comment by mbonsma** [comment]
And by 'makes sense' I mean 'seems like a good idea'. I don't know much about efficient data pipelines.

**Comment by JJ** [comment]
Are you available now? Instead of going back and forth we could chat this
out. I'm jjmerelo at gmail or Skype if you prefer (I don't, but well...)

2015-06-10 17:36 GMT+02:00 mbonsma <notifications@github.com>:

> And by 'makes sense' I mean 'seems like a good idea'. I don't know much
> about efficient data pipelines.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goyalsid/phageParser/issues/46#issuecomment-110800331>
> .
>



-- 
JJ

**Comment by mbonsma** [comment]
We can talk now, sure. Do you mean google hangouts or chat?

**Comment by mbonsma** [comment]
Closing - we decided on an approach to deal with the issue causing this bug - see issue #47

**Comment by daisieh** [comment]
@JJ, this is why I don't read the entire file in at once.
