### ISSUE TITLE
Change filterByExpect.py to use SeqIO blast parser

### ISSUE THREAD

**Issue by mbonsma** [goyalsid/phageParser#48]
I haven't fully read up on this, but we should probably be using [Biopython's built-in blast parser](http://biopython.org/DIST/docs/tutorial/Tutorial.html#sec:parsing-blast) to deal with the blast output. 
Here's why:
- Blast+ keeps changing, and each time the format of the output files changes as well, so the parser will be hard to maintain with regular expressions.
- It will be much quicker than the current version, which uses a complicated (and probably slow, as pointed out by @JJ) regex. 

Some things:
- the output of blast should be XML - this is easy to do, all that's needed is to change the output format in the BlastLoop.py script. 
- for now, we might as well save all the features of the record (unless that's really dumb). 

This means `phage_file_2_2_30.py` will need to be updated, which is where the machinery of the parsing for `filterByExpect.py` is located. There's a `parse` function with a really long regex, you'll know it when you see it.

**Comment by mbonsma** [comment]
For future reference: in the Blast+ options, including `-outfmt=5` will give you xml output.

**Comment by mbonsma** [comment]
@shirishgoyal, do you have any opinions on this? I don't really understand the whole class structure in Python, so if I were to do this I would be writing an entirely new script as opposed to tweaking things in `phage_file_2_2_30.py` and `filterByExpect.py`. It might be good for us to chat briefly so you can explain to me what those scripts really do :)

**Comment by mbonsma** [comment]
I just pushed `filterByExpect_all_v2` (here's the [commit](https://github.com/goyalsid/phageParser/commit/4658c1373a7c8866a88a16042244f7d84b940b97)) which produces the same result as `filterByExpectPhages.py` but uses the NCBIXML parser.

**Comment by shirishgoyal** [comment]
@mbonsma, it is just a way to organize basically and write DRY code. I will take a look at what you pushed in. My objective is mainly to turn this package into a suite like BioPython which focuses mainly on Phages/Virii even if it is a module that integrates with BioPython.

I do not have much understanding of Biology aspects but would love to learn as much as possible. This project was missing someone active like you to answer some of those queries and therefore I could only based on the description provided for the earlier sprint problems.

**Comment by mbonsma** [comment]
@shirishgoyal Thanks, that would be great if you could take a look! 

I agree that it would be nice to have the class structure like BioPython. I sort of understand how to use classes, but I don't understand the creation part. Thanks for your contributions already, they've been great and very helpful, and I'll do my best to answer any biology-related things I can.

**Comment by shirishgoyal** [comment]
Can we use something like slack.com or hipchat for more real-time discussion?

**Comment by mbonsma** [comment]
Sure, slack works. I made a [slack team](https://phageparser.slack.com/) - do I need to invite you now? (I haven't used slack before.)

**Comment by shirishgoyal** [comment]
Yes, please send me an invite at shirish.goyal@gmail.com
