### ISSUE TITLE
Bharat Shetty Barkur: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by bsbarkur** [goyalsid/phageParser#5]
I've been interested in Bioinformatic data analysis since my stint at a Comp-Bio company. I want to contribute to open source in this arena.<p><br><blockquote>This issue was created by @bsbarkur via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Hi Bharat, sorry for leaving you hanging for so long! I'm Madeleine, a new project leader on this project. Your expertise in bioinformatics would be valuable for this project; are there specific things that you've seen here that you'd particularly like to work on?
