### ISSUE TITLE
Andrew Clarkson: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by bitborn** [goyalsid/phageParser#50]
Interested in learning about python for genome analysis<p><br><blockquote>This issue was created by @bitborn via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Welcome! My name is Madeleine, I'm one of the project leads. I'm a Master's student in the Physics department at the University of Toronto. 

I'm continuing to learn a lot from contributors in this project about good ways to use python for genome analysis. Let me know if there's anything in particular in the issues that looks cool to you.
