### ISSUE TITLE
Darwin Hang: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by darwinhang** [goyalsid/phageParser#51]
I'm a former geneticist (now web developer) looking to contribute to Open Source.<p><br><blockquote>This issue was created by @darwinhang via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Welcome! My name is Madeleine, I'm one of the project leads. I'm a Master's student at the University of Toronto in the physics department. 

Thanks for your input already (#49)! Please feel free to make any other suggestions or jump in on an existing issue that looks cool. I'll try my best to clarify things if you have questions - this project is evolving a lot as we go.

**Comment by darwinhang** [comment]
Awesome. Thanks for the warm welcome!
