### ISSUE TITLE
Need CONTRIBUTING.md

### ISSUE THREAD

**Issue by mbonsma** [goyalsid/phageParser#57]
We don't have any contributor guidelines! For now, it should just have these things:
- a friendly welcome message for contributors 
- a note saying we accept contributions in any programming language, but most things have been done in Python
- a link to the README.md file

Possible future extensions:
- a description of issue tags we use
- a link to the Code of Conduct (we don't have one yet though)
- a link to a place to ask general questions
- guidelines and/or a link to a place to request features

Mozilla Science Lab's [exercise](http://mozillascience.github.io/working-open-workshop/contributing/) for making a CONTRIBUTING.md is a useful resource! (Thanks @acabunoc)
Check out [paperbadger's](https://github.com/mozillascience/PaperBadger/blob/master/CONTRIBUTING.md) as an example - this one is pretty fleshed out, ours needn't be at this point.

**Comment by acabunoc** [comment]
http://mozillascience.github.io/working-open-workshop/contributing/

**Comment by mbonsma** [comment]
Here's a start, but it's very basic still: https://github.com/goyalsid/phageParser/blob/master/CONTRIBUTING.md
