### ISSUE TITLE
Add more info describing CRISPR system and diagram of locus to README.md

### ISSUE THREAD

**Issue by mbonsma** [goyalsid/phageParser#59]
The README needs a bit more information on the technical details of the CRISPR system. A high-level description geared at a lay-person would be great. It should go in the "About the CRISPR system" section of the README.
- Include [this diagram](https://github.com/goyalsid/phageParser/blob/master/CRISPR_locus_diagram.png) of the CRISPR locus

**Comment by lpix** [comment]
I have added more info on the CRISPR system and included the diagram.

**Comment by mbonsma** [comment]
Fixed in #93
