### ISSUE TITLE
WebDevByEdd: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by WebDevByEdd** [goyalsid/phageParser#61]
Hey! I have done some Python testing before, so I can look at that, plus I'd love to help in any other way I can :) <p><br><blockquote>This issue was created by @WebDevByEdd via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
That would be awesome! You probably saw the issue about testing (#18) - there's been some discussion on it already. I'm not an expert on tests, but it sounds like there needs to be some cleanup first to parametrize some things, make classes, and make packages. If you think that's an easy task, I can make a separate issue as a "good first bug" that involves cleanup, and either you or someone else could do that, and maybe you could create some tests?

And feel free to take a crack at any other issue listed!
