### ISSUE TITLE
Help develop a Code of Conduct!

### ISSUE THREAD

**Issue by mbonsma** [goyalsid/phageParser#63]
We're lacking a Code of Conduct - this is a document that explains the kind of community we want to have here and what to do if things go awry. 

I'm looking for someone who'd be willing to help me craft a Code of Conduct. This could involve one or two Google Hangouts or just some emailing back and forth. Here's a possible template: [Mozilla Science Lab's CoC](https://www.mozillascience.org/code-of-conduct). Ours will be less about events and more about online community.  

We've started a draft code of conduct [here](https://github.com/goyalsid/phageParser/blob/master/CODE-OF-CONDUCT.md) that so far just links to the Mozilla Participation Guidelines.

**Comment by souravsingh** [comment]
Hello! I would like to help in this project.

**Comment by mbonsma** [comment]
Hi @souravsingh, welcome! What kind of things are you interested in working on? [This section](https://github.com/goyalsid/phageParser/blob/master/README.md#where-can-i-get-involved) of the README lists a few areas we're focusing on now.

**Comment by souravsingh** [comment]
@mbonsma I am looking to help in this issue.

**Comment by mbonsma** [comment]
@souravsingh oh great! Sorry I mixed that up. 

So as of now our code of conduct is just a link to Mozilla's code of conduct, but it would be nice to have our own, based on theirs. Do you have any suggestions for the kinds of themes that could be included?

**Comment by souravsingh** [comment]
We can take ideas from here- https://github.com/ContributorCovenant/contributor_covenant

**Comment by mbonsma** [comment]
That's a great one - maybe we can paste it in (with attribution) and start editing from there?

**Comment by souravsingh** [comment]
Sure, I will send a PR right now
