### ISSUE TITLE
Discuss and research database options

### ISSUE THREAD

**Issue by mbonsma** [goyalsid/phageParser#64]
Ultimately this project will be a database that stores the results of all the analyses developed, that people can query in different ways. 

I'm not familiar with databases or what options are out there, so I'd like to hear from people who know about or use databases - what are the pros and cons of different options? I'm available to email or Google Hangout to discuss.

**Comment by lwgray** [comment]
The only database I am familiar with is postgresql but maybe if we can decide what the criteria that we need meet then I can run it by our database guy in the Structure Group

**Comment by mbonsma** [comment]
PostgreSQL looks cool. What might be helpful is if we could find or someone could comment on some of the options and what situations they're applicable for. Something like [this Quora answer](https://www.quora.com/Which-database-should-I-use), and then we can try to match that to the project needs.

**Comment by dbonsma** [comment]
What will your data look like? i.e. is it very structured or very unstructured? How much data will there be?  What do you intend to do with it? Where will it reside? Who will maintain the database? How will you retrieve data from it?

Here is some good basic info on a few choices: https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems

I assume you want open source, which means I would look at PostgreSQL or MySQL.  I have used MySQL a few times in the past and have been quite impressed with it. I have not used PostgreSQL, but it's been around for a long time and has a good reputation.  I know that MySQL is easily installed on a PC, or on a network server, or on a Linux box and many websites offer MySQL database support as an online database. I can't tell you how much of that is true for PostgreSQL although I expect it to be a bit more difficult to install and maintain, due to it being considered a bit more high-end than MySQL. Your answer to the question "where will it reside?" will partly determine your options.

**Comment by mbonsma** [comment]
> What will your data look like? i.e. is it very structured or very unstructured? 

I think it would be considered fairly structured, but potentially changing every few days or weeks.

> How much data will there be? 

Not a lot: we're talking 1s to 10s of GB, and on the order of thousands of entries. 

> What do you intend to do with it? Where will it reside? Who will maintain the database? 

Ultimately it will reside on a server somewhere, and be maintained by me and my successors. It will serve as the back end for a GUI of some sort that anyone can access through the web. 

> How will you retrieve data from it?

No idea!

**Comment by mbonsma** [comment]
I'm looking at [Heroku](https://dashboard.heroku.com/) as a possible place to host things (possibly just until our lab gets a server, possibly forever), and [it seems like they use PostgreSQL](https://devcenter.heroku.com/articles/getting-started-with-python#introduction).

**Comment by pydevhacker** [comment]
There are many aspects to think about DB. SQL / NSQL/ Open source/ Structured / unstructured /volume of data/ frequency of data/ relation between data.

We can think of MongoDB also, Heroku has support for MongoDB as well.
In MongoDB data is stored as a Document (in form of JSON documents). Its easy to store and extract data. Its a salable solution.

If data schema is changing frequently then RBMS is not a good option. Its an overhead to maintain schema. If we are certain that our schema will not change then we can think of RDBMS.

Can you please provide a sample data to get better understanding of data we will be deailling?

**Comment by mbonsma** [comment]
@pydevhacker, all great points. I don't think the schema will be changing much - new categories might be added occasionally, but what's already in place would be fairly static. 

Here's a toy example of what a row in the database might look like:

| Organism  | CRISPR locus position  | CRISPR repeat sequence | *cas* genes |  Inferred CRISPR type | Phage database matches |
| ------------- |:-------------:| -----:| -----:| -----:| -----:|
| Acidobacterium capsulatum ATCC 51196 | 894165 - 895723 | GTTTCAATCCAC GCGCCCGCGAG GGGCGCGAC | Cas1, Cas2, Cas3, Cas4, Csd1, Csd3, Csd5 | Type I | Bacillus phage Hakuna, Escherichia phage vB_EcoM_ECO1230-10, ... |

There would be many more entries in some of the columns, and there would also be many more columns, but that's the general idea.

**Comment by Maritimesailor** [comment]
@mbonsma Have you looked into mongodb as the database to use for the project? And I'm new here hello all!

**Comment by dbonsma** [comment]
Is your database just going to consist of that one table that you gave us a sample of, or are there going to be multiple, related tables? I'm interested in some more detail on what is actually in your columns. Your sample shows variable comma-separated values in a single column. Are you planning to parse that out later? When you say there would be "many" more entries in some columns, and "many" more columns, how many are you referring to?  From your small sample, it looks like you might be trying to describe in a flat file what could actually be stored in a set of related tables, but I may be misreading that.  

Your earlier answer to my question of "is it very structured data" was that you think it's structured, but may change every few days or weeks. What is changing, exactly, is it the schema or the data itself? I agree with an earlier comment that if the schema changes often, then RDBMS may not be the best option, but I'm not sure that's the case, based on what you've said so far.  I have not used MongoDB, but from what I've read and what you've shared, I would still lean to PostgreSQL.

**Comment by mbonsma** [comment]
@dbonsma - yes, I think a set of related tables might be better. "Many" is in the tens to several hundreds range. 

Pinging @a8wright - relevant to our discussion.

**Comment by nicolanrizzo** [comment]
Another idea for hosting is [Amazon RDS](https://aws.amazon.com/rds/). Companies like AirBnb and FlipBoard are using it. For pricing read [here](https://aws.amazon.com/rds/pricing/).

I was thinking also that we can use a good [ORM](https://en.wikipedia.org/wiki/Object-relational_mapping) like [SQLAlchemy](http://www.sqlalchemy.org/): the database will be much more easy to maintain and change in future.

Both Amazon RDS and SQLAlchemy are compatible with Postgresql and MySQL, among others; and, of course, SQLAlchemy is compatible with Amazon RDS.

**Comment by pydevhacker** [comment]
@mbonsma If you are not concerned about real time data and transaction then NoSQL would be a good option. As per your data, document based db will work fine. Mongo DB or Couch DB will be a good option. You can add remove and update any column and it will not effect any change in DB option.

here data is limited and no frequent updates are happening then you can use simple db. 
MySQL will also work.  Its a good practice to keep things simple :)

**Comment by mbonsma** [comment]
ER diagram from @dbonsma:

![image](https://cloud.githubusercontent.com/assets/5651370/15787773/221e3280-2992-11e6-9329-ae0caddfbeb1.png)

**Comment by mbonsma** [comment]
We're starting with sqlite, possibly switching to PostgreSQL.
