### ISSUE TITLE
Larry Gray: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by lwgray** [goyalsid/phageParser#65]
My computational biology background could be an asset plus the codebase for this project has similarity to my side project<p><br><blockquote>This issue was created by @lwgray via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
@lwgray, welcome! Computational biology is indeed a great asset. Are you interested in helping more on the science or code side of things, or both?

**Comment by lwgray** [comment]
Both... I work in structural Computation biology so I have limited genomic
expertise but I am willing to learn.

I was looking at some of the issues last night but probably need to speak
with you over google hangout to get a better understanding.

Cheers,
Larry

**Comment by mbonsma** [comment]
We can definitely chat on Google Hangout sometime. Send me an email at m.bonsma@mail.utoronto.ca and we can set up a time!
