### ISSUE TITLE
Vikram Singh Sikarwar: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by pydevhacker** [goyalsid/phageParser#67]
Hi, I am a python developer and love machine learning to solve real world problem. With this project I want to learn and contribute in field of diagnosis. <p><br><blockquote>This issue was created by @vsikarwar87 via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Welcome @pydevhacker! We are always in need of Python developers. Just to be clear though, we're not planning to use any machine learning in the project, and diagnosis isn't the subject of the project - when we say "immunity", we're actually talking about bacterial immunity to viruses! 

Is there anything in particular that caught your eye that you'd like to work on? We've marked some [good first bugs](https://github.com/goyalsid/phageParser/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+bug%22) that are good tasks for people new to the project!

**Comment by pydevhacker** [comment]
Thanks @mbonsma 
I have started with db discussion.
