### ISSUE TITLE
lpix: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by lpix** [goyalsid/phageParser#69]
Hi! 
I was hoping to find projects that I could do to get more programming experience in Biology, and I am glad I found this group! 
I am new to GitHub and OpenSource Science/Programming in general, so I have to get used to the system first. I am looking forward to working with you!
Cheers,
Leslie<p><br><blockquote>This issue was created by @lpix via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Hi Leslie, welcome! It's great that you're interested! If you're looking for a good intro issue to tackle, check out issue #59. You could even just do the photo insert part and leave the rest for someone else if you wanted to. 

I'd be happy to chat sometime over Skype or Google Hangout if you want to hear more about the project!

**Comment by lpix** [comment]
Thank you @mbonsma! This looks like a good first project, I'd be happy to work on it. I don't have Google or Skype, I do have Facebook or e-mail is fine as well (I don't know if GitHub has any private messaging?)

**Comment by mbonsma** [comment]
My email is m.bonsma@mail.utoronto.ca if you'd like to chat, but no pressure!
