### ISSUE TITLE
Maritimesailor: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by Maritimesailor** [goyalsid/phageParser#71]
I am interested in advancing science and helping the medical, I am a college student studying computer science in the US.<p><br><blockquote>This issue was created by @Maritimesailor via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Hi @Maritimesailor, welcome! This project is about trying to learn as much as possible about the CRISPR system from data that's already publicly available. It doesn't really have any medical applications, it's more on the fundamental science side. 

If you're looking for something to dive into, check out the [good first bugs](https://github.com/goyalsid/phageParser/labels/good%20first%20bug), and particularly the [code](https://github.com/goyalsid/phageParser/labels/code) label if you'd like to program some stuff. If you're more interested in helping on the documentation or science side of things, there are some [good first bugs](https://github.com/goyalsid/phageParser/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22good+first+bug%22+label%3A%22documentation%22+) in that area too!

**Comment by Maritimesailor** [comment]
Since I'm new to coding I think I'll look at  good first bugs. Thank you!
