### ISSUE TITLE
Make class to check if bacterial/archaeal genomes are up-to-date

### ISSUE THREAD

**Issue by mbonsma** [goyalsid/phageParser#74]
Several scripts will want to know if the bacterial and archaeal genomes in our database are up-to-date. This class will contain some functions to (a) check if the genome is present and up-to-date and (b) download it from NCBI if necessary.

---
### The Class

@lwgray suggested a class instead of a script for this task, so the following should come in a class wrapper for easy access.

**Input:**
- Accession number of organism - i.e. NC_000853.
- Optional time window `t` (in months) - if date downloaded is more than `t` months ago, re-download from NCBI.

**The function should do the following:**
- Check if the genome of the organism has already been downloaded - i.e., is it in `phageParser/data/prokaryote_genomes`?
- If it hasn't been downloaded OR if it is more than `t` months out of date, fetch the genome from NCBI using [acc2gb.py](https://github.com/goyalsid/phageParser/blob/master/acc2gb.py).

Note: this was based on a discussion from Issue #60.

**Comment by mbonsma** [comment]
Pinging @lwgray since you've made progress on this one.

**Comment by Ky5595** [comment]
I would like to resolve this issue.
Is this still open ?

**Comment by mbonsma** [comment]
Hi @Ky5595, this one had some work done on it and I think is pretty much finished. Thanks for the heads up, I'll close this one.
