### ISSUE TITLE
gxn1710: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by gxn1710** [goyalsid/phageParser#78]
Hello, everyone! My name is Gaurav, and I am a second-year undergraduate who is interested in the data processing aspects of this project. Right now, I am looking into the "good first bugs" and will hopefully start committing changes soon. Since I am more interested in the coding aspect of this project, are there any other tasks that you guys think I would be a good fit for?<p><br><blockquote>This issue was created by @gxn1710 via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Hello Gaurav, welcome! You're right, anything marked [good first bug](https://github.com/goyalsid/phageParser/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+bug%22) or [code](https://github.com/goyalsid/phageParser/issues?q=is%3Aissue+is%3Aopen+label%3Acode) would probably be up your alley. Ping me or send me an email at m.bonsma@mail.utoronto.ca if you want to chat more in depth!
