### ISSUE TITLE
José: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by jobliz** [goyalsid/phageParser#8]
I'm a Python developer with numpy/scipy experience, coming from a year working with solid state kinetics. I know this is quite a different field from this project's focus, but current epidemics have made me become interested in bioinformatics, and given that I've seen that it is indeed possible to use my knowledge of solid state kinetics in pharmaceutical topics, this project has gotten my interest. Since I need to delve into the necessary literature in order to understand context (I'm no biologist), I'd appreciate some suggestions. It'd be nice to have an update in the GitHub readme with suggested literature to start drilling into this topic.<p><br><blockquote>This issue was created by @jobliz via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Hi José, sorry for the very delayed reply! I've recently become a project leader here, and if you're still interested in contributing we'd love to have you. My own background is in physics with very little bioinformatics as well.

I created an issue ( #19) with your recommendation to add some suggested literature - good idea! I will address that as soon as I can.
