### ISSUE TITLE
Convert BLAST_loop.py to command line input

### ISSUE THREAD

**Issue by mbonsma** [goyalsid/phageParser#83]
The script [`BLAST_loop.py`](https://github.com/goyalsid/phageParser/blob/master/BLAST_loop.py) is currently set up with the directory hardcoded [here](https://github.com/goyalsid/phageParser/blob/master/BLAST_loop.py#L21). This should be changed so that it can be run from a command prompt as

```
python BLAST_loop.py directory
```

The function [acc2gb.py](https://github.com/goyalsid/phageParser/blob/master/acc2gb.py) operates kind of like this, as an example.

**Comment by aays** [comment]
Hey @mbonsma! I'm still a little new to programming command line arguments, but does replacing that hardcoded directory with the following two lines work?

`for arg in sys.argv:`
   ` directory = arg `

**Comment by mbonsma** [comment]
Fixed in PR #84.

**Comment by aays** [comment]
Got it! That looks like a much more elegant solution too.

**Comment by mbonsma** [comment]
@aays yes, I think you're right! Sorry for the traffic jam, we were working on that but forgot to comment as such.
