### ISSUE TITLE
Script to BLAST antiCRISPR genes against host genome

### ISSUE THREAD

**Issue by mbonsma** [goyalsid/phageParser#89]
1. Download antiCRISPR gene sequences
2. BLAST against genomes

This can be two functions: the first to download the antiCRISPR genes, and the second to BLAST.

The second function should take an accession number for an organism (i.e. NC_000853) and blast the known antiCRISPR genes, saving the output as XML.

Issue #60 is similar but for spacers - look there for more info!

**Comment by mbonsma** [comment]
@aays, this is for you!

**Comment by aays** [comment]
I just realized this -- it appears that all the accession numbers for the antiCRISPR genes bring up protein sequences and not nucleotide sequences when searched with Entrez. Would I be using tblastn then to BLAST them against genomic data? Or is there something I'm missing?

**Comment by mbonsma** [comment]
@aays good point. I'll ask April (whose lab got these sequences) if she recommends nucleotide or protein blast. If nucleotide, we'll need to get the nucleotide sequences from them as well. 

We could try, in the meantime, using blastp (protein blast) on the translated coding regions of each organism. The genbank files ([example here](https://github.com/goyalsid/phageParser/blob/master/data/Genbank_example.txt)) also come with translations.

**Comment by mbonsma** [comment]
Issue #70 is linked to a function that, among other things, extracts the protein translations from a genbank file. You could probably re-use some of this! Or even split it into chunks that can be re-used.

**Comment by mbonsma** [comment]
Here's the function: [PFAM_db.py](https://github.com/goyalsid/phageParser/blob/master/PFAM_db.py)

**Comment by mbonsma** [comment]
[This blast syntax](https://github.com/goyalsid/phageParser/blob/master/BLAST_loop.py#L33) should still apply, you'd just have to change `db = 'nuccore'` to `subject = 'bac_genome.fasta'`

**Comment by aays** [comment]
Got it!

**Comment by aays** [comment]
I'm about ready to upload phageblast.py, which addresses the second part of the problem and is more or less ready to go -- however, I keep encountering a 400 Bad Gateway error, which the report indicates has to do with fetching the organism's genome given an accession number in the command line arguments. I'm going to try troubleshooting further after I leave the lab today, but in the meantime do you know what the problem might be?

**Comment by mbonsma** [comment]
I'm not sure what that is. What command is giving you the error? Is it blast? 

The genome you blast against should already be downloaded from the script's perspective, so you only need to fetch the protein sequences.

**Comment by aays** [comment]
Ah, I misunderstood! I included a command to fetch the genome, and that was what kept giving me an error, but if the genome is already downloaded from the script's perspective then that isn't necessary in the first place. I assumed that the function taking an accession number for an organism as input involved the genome being downloaded as part of the script.

**Comment by aays** [comment]
I should add that for some reason, using cat <input file> in the bash command kept giving me blank .xml files as output, but switching that to echo <input file> did the trick. I feel like this is a bit of a clumsy workaround, and if that is the case, any advice would be appreciated!

**Comment by mbonsma** [comment]
Completed by @aays! :clap:
